* File Configuration                                       :ARCHIVE:noexport:
#+TITLE: Ridehail simulation
#+AUTHOR: Tom Slee
#+LATEX_CLASS: article
#+OPTIONS: H:3 toc:t num:t ':t arch:nil d:nil prop:nil tags:nil todo:nil
#+STARTUP: content indent beamer noalign inlineimages latexpreview
#+STARTUP: logdone logdrawer hideblocks  hidestars hideblocks
#+TODO: TODO(t) PROJ(p) NEXT WAIT(w@/!) | DONE(d@) CANCELLED(c@)
# #+SETUPFILE: ~/prodmgmt/org/org-html-themes/setup/bigblow-pirilampo.setup


* Ridehail simulation

This is a personal project. You're welcome to use it but don't expect anything.

* Running a simulation

- Read example.config
- Make a copy of example.config, eg <username>.config
- Run "python ridehail.py -@ <username>.config (or whatever you called it)
- Try making other changes to your config files

There is also a set of example files in the config directory.

* Inspiration

This project is inspired by a New York Times animation with this title, published on April 2, 2017. The animation was a simple simulation of a ridehail system for exploring how wait times and driver efficiency (fraction busy) are related.

The NYT animation is [[https://www.nytimes.com/interactive/2017/04/02/technology/uber-drivers-psychological-tricks.html][here]], but in case the link is broken I captured the video [[file:output/nyt_ridehail.mp4][here]]. It shows a 9 * 40 grid city with around 50 requests at the beginning. The number of drivers can be chosen from 50, 75, 125, or 250. The wait time and percent of drivers idling goes as follows:

| Drivers | Wait time (mins) | Drivers idle (%) |
|---------+------------------+------------------|
|      50 |               18 |                2 |
|      75 |               12 |                5 |
|     125 |                5 |               50 |
|     250 |                3 |               71 |

Idle time does not include time heading to pick up the passenger. At the end of each trip the riders vanish and the drivers stay still.

There is also a rider at the top of the bottom-left block, who vanishes.

A rider in the very bottom left edge gets picked up after three seconds, and it taken all the way to the top, along to the right edge, and back down to the bottom right corner before being dropped off.

At the beginning of the simulation there is a rider in the top left corner. Not picked up after several seconds, the rider just vanishes.

In reply, Uber, [[https://www.uber.com/newsroom/faster-pickup-times-mean-busier-drivers/][here]], argues that "This is simply not true... When Uber grows in a city: riders enjoy lower pick-up times /and/ drivers benefit from less downtime between trips. It's a virtuous cycle that is widely acknowledged in [[https://twitter.com/davidsacks/status/475073311383105536?lang=en][business]] and [[https://www.nber.org/papers/w22083][academia]], and which is backed up by data."

The "business" link is to a tweet with a napkin sketch. The "academia" link is to Cramer and Kruger, of which more below. The links are accompanied by charts---with no y axis labels---showing that in major cities the driver idle time (median percent of time not with a rider) has shrunk, along with ETA (wait time), in five major US cities from June 2014 to June 2015 to June 2016 as the number of drivers has grown.

This is a comparisons of apples to oranges, and the lack of a Y axis scale makes the Uber claims dubious, but it still suggests something worth investigating.

Here is the rest of Uber's explanation:

#+begin_quote
How is this happening? First, as the number of passengers and drivers using Uber grows, any individual driver is more likely to be close to a rider. This means shorter pickup times and more time spent with a paying passenger in the back of the car. In addition, new features like uberPOOL and Back-to-Back trips have meant longer trips, while incentives to drive during the busiest times and in the busiest locations help keep drivers earning for a greater share of their time online. And that should be no surprise: drivers are our customers just as much as riders. So although the Times article suggests that Uber’s interest is misaligned with drivers’, the opposite is true: it’s in our interest to ensure that drivers have a paying passenger as often as possible because they’re more likely to keep using our app to earn money. (And Uber doesn’t earn money until drivers do.)
#+end_quote

* Capacity utilization: other reports

Deadheading refers to the time or distance without a rider in the car. If a driver waits where they are between rides, these two measures may be quite different.

** Driver phases

Ride-hail insurance commonly uses these phases
- Phase 0: App is off. Your personal policy covers you.
- Phase 1: App is on, you're waiting for ride request. 
- Phase 2: Request accepted, and you're en route to pick up a passenger.
- Phase 3: You have passengers in the car.

** Schaller, The New Automobility

From Bruce Schaller (/The New Automobility/) [[http://www.challerconsult.::com/rideservices/automobility.pdf][here]].

#+begin_quote
Working against the efficiency of Uber and Lyft is the large proportion of mileage without a paying passenger in the vehicle. For a typical passenger trip of 5.2 miles, a TNC driver travels three miles waiting to get pinged and then going to pick up the fare.
#+end_quote

This corresponds to a P3 fraction of about 65%.

Schaller from Empty Seats, Full Streets:

#+begin_quote
In 2017 TNCs had 55K hours with passengers in the Manhattan Central Business District (CBD), and 37K hours without passengers (60% busy).

While yellow cabs were occupied with passengers 67 percent of the time in 2013, the utilization rate for combined taxi/TNC operations dropped to 62 percent in 2017.
#+end_quote

** John Barrios

> “Rideshare companies often subsidize drivers to stay on the road even when utilization is low, to ensure that supply is quickly available,” they wrote.

** Cramer and Krueger

In [[https://www.nber.org/papers/w22083.pdf][Disruptive Change in the Taxi Business: The Case of Uber]], Cramer and Krueger write:

#+begin_quote
Capacity utilization is measured either by the fraction of time that drivers have a farepaying passenger in the car or by the fraction of miles that drivers log in which a passenger is in the car. Because we are only able to obtain estimates of capacity utilization for taxis for a handful of major cities – Boston, Los Angeles, New York, San Francisco and Seattle – our estimates should be viewed as suggestive. Nonetheless, the results indicate that UberX drivers, on average, have a passenger in the car about half the time that they have their app turned on, and this average varies relatively little across cities, probably due to relatively elastic labor supply given the ease of entry and exit of Uber drivers at various times of the day. In contrast, taxi drivers have a passenger in the car an average of anywhere from 30 percent to 50 percent of the time they are working, depending on the city. Our results also point to higher productivity for UberX drivers than taxi drivers when the share of miles driven with a passenger in the car is used to measure capacity utilization. On average, the capacity utilization rate is 30 percent higher for UberX drivers than taxi drivers when measured by time, and 50 percent higher when measured by miles, although taxi data are not available to calculate both measures for the same set of cities.

Four factors likely contribute to the higher utilization rate of UberX drivers: 1) Uber’s more efficient driver-passenger matching technology; 2) Uber’s larger scale, which supports faster matches; 3) inefficient taxi regulations; and 4) Uber’s flexible labor supply model and surge pricing, which more closely match supply with demand throughout the day.
#+end_quote

They report these capacity utilizations (% of hours with a passenger).

| City    | TNC | Taxi | TNC Distance | Taxi Distance |
|---------+-----+------+--------------+---------------|
| Boston  | 47% | NA   |              |               |
| LA      | 52% | NA   |          64% |           41% |
| NYC     | 51% | 48%  |              |               |
| SF      | 55% | 38%  |              |               |
| Seattle | 44% | NA   |          55% |           39% |

Also, for LA and Seattle, they report capacity utilization rates by distance (percent of miles driven with a passenger). These have been added in above. The higher distance values show that some drivers may stay still when waiting for a ride.

** TNCs Today: SFCTA report (2017)

The report is [[https://archive.sfcta.org/sites/default/files/content/Planning/TNCs/TNCs_Today_112917.pdf][here]]. In the report, "Out-of-service VMT [vehicle miles travelled] refers to the vehicle miles traveled while circulating to pickup a passenger." It is not clear if this includes P3 time and distance.

#+begin_quote
Approximately 20% of total TNC VMT are out-of-service miles. This is significantly lower than the more than 40% of taxi VMT that are out-of-service miles... The greater efficiencies of TNCs, as
reflected in a lower share of out-of-service miles, are likely
primarily a reflection of the larger fleets of TNC drivers operating on the road at any given time, enabling shorter distances to pickup locations. 
#+end_quote

Table 4 (weekdays) is similar to tables 5 and 6 (weekends).

| Quantity                           | TNC       | Taxi       |
|------------------------------------+-----------+------------|
| Trips                              | 170K      | 14K        |
| Average trip length                | 3.3 miles | 4.6 miles  |
| Average in-service trip length     | 2.6 miles | 2.6 miles  |
| Average out-of-service trip length | 0.7 miles | 2.0 miles  |
| Percent out-of-service trip length | 21%       | 44%        |

The data used in this study was collected from the Uber API. "Sending a request to the API returns a text file response containing this information [nearby vehicle locations, estimated times-to-pickup, and more]. I am sceptical of the data here.

** Alejandro Henao, University of Colorado at Denver, Master's Thesis (2013)

Based on his own experience.

| Phase                    | Time (minutes) |
|--------------------------+----------------|
| Available                |             12 |
| Pickup                   |              6 |
| Wait for pax             |              1 |
| Ride                     |             15 |
| Going home at end of day |             22 |

| Phase                    | Distance (miles) |
|--------------------------+------------------|
| Available                |              1.5 |
| Pickup                   |              1.5 |
| Trip                     |                7 |
| Going home at end of day |               12 |

#+begin_quote
The time efficiency rate of a ridesourcing driver based on the time a passenger is in the car and total time from driver log-in to log-out (not accounting for the commute at the end of the shift) is 41.3%, meaning that I, as a driver, during my shift hours spent more time without a passenger than with one in the car... When accounting for commuting time at end of shift, the time efficiency rate drops to 39.3% of total time... Lyft and Uber drivers travel an additional 69.0 miles in deadheading for every 100 miles they are with passengers.
#+end_quote

** Uber blog

This Uber blog post from 2015 is about [[https://www.uber.com/en-GB/blog/london/how-efficiency-benefits-riders-and-partners/][efficiency]].

#+begin_quote
Since uberX launched in London in July 2013, average pick-up times – the time between requesting and your car arriving – have reduced from 6 and a half minutes to just over 3 minutes.

| Year | pick-up time (minutes) | P3 % by time |
|------+------------------------+--------------|
| 2013 |                    6.3 |           17 |
| 2014 |                    4.3 |              |
| 2015 |                    3.1 |           57 |

Back in 2013, when uberX launched in London, partners had a passenger in their car for 16 minutes of every hour. Now that number has more than doubled to 34 minutes.
#+end_quote

