---
title: 'Ridehail Notebooks: Sequences'
output:
  html_document:
    df_print: paged
---

# A sequence 


```{r include=FALSE}
# install.packages("librarian")
librarian::shelf(tidyverse, ggplot2, reshape2, ggtext, jsonlite, stringr)
```

```{r echo=FALSE}
sequence_plot <- function(filename_root){
  jsonl_file <- paste(filename_root, ".jsonl", sep="")
lines <- readLines(jsonl_file)
config <- lapply(lines[1], fromJSON)
config <- lapply(config, unlist)
config <- bind_rows(config)
annotation = str_glue("City size={config$config.city_size} blocks<br>
                      Request rate={config$config.base_demand} per block<br>
                      Trip inhomogeneity={config$config.trip_inhomogeneity}")
sequence <- read_csv(file=str_glue("{filename_root}.csv", sep=""))
sequence$idx <- 1:nrow(sequence)
# convert to a long form
longseq <- melt(sequence, 
                measure.vars = c("vehicle_fraction_idle", 
                                 "vehicle_fraction_picking_up", 
                                 "vehicle_fraction_with_rider", 
                                 "mean_trip_wait_fraction")
                )
  colours <- c("vehicle_fraction_idle" = "royalblue3", "vehicle_fraction_picking_up" = "gold3", "vehicle_fraction_with_rider" = "green3", "mean_trip_wait_fraction" = "red3")
  linetypes <-  c("vehicle_fraction_idle" = "solid", "vehicle_fraction_picking_up" = "solid", "vehicle_fraction_with_rider" = "solid", "mean_trip_wait_fraction" = "dashed")
  labels <- c("vehicle_fraction_idle" = "P1 (available)", "vehicle_fraction_picking_up" = "P2 (dispatch)", "vehicle_fraction_with_rider" = "P3 (busy)", "mean_trip_wait_fraction" = "Wait fraction (W/L)")
  p <- ggplot(data=longseq, mapping=aes(x=mean_vehicle_count, y=value, colour=variable, linetype=variable, label=annotation))
  p + geom_point(alpha=0.5, size=2) +
    geom_line(stat="smooth", data=subset(longseq, mean_vehicle_count > 850), alpha=0.5, size=1) +
    scale_x_continuous(minor_breaks = seq(0, 5000, 50), breaks = seq(0, 5000, 200)) +
    scale_y_continuous(limits=c(0,1), minor_breaks = seq(0 , 1, .05), breaks = seq(0, 1, .2)) +
    scale_linetype_manual(values=linetypes, labels=labels) +
    scale_colour_manual(values=colours, labels=labels) + 
    xlab("Vehicles") +
    ylab("Fraction") + 
    ggtitle(config$config.title) +
    geom_richtext(aes(x=1200, y=1.0, label=annotation, width=unit(0.3, "npc"), stat="unique"),
                 size=3.2, 
                 lineheight = .9,
                 color="black", 
                 fill="white", 
                 hjust = "left",
                 vjust= "top",
                 label.colour = "white",
                 show.legend = FALSE) +
    # theme(axis.line = element_line(colour="darkgrey", size=1))
    theme(legend.position = c(0.2, 0.85), 
          legend.background = element_rect(fill=alpha("lightgray", 0),
                                    size=0.5, linetype="blank", 
                                    colour ="lightgray"),
          legend.key=element_rect(fill = alpha("white", 0)),
          legend.title = element_blank(), 
          legend.margin=margin(t=-0.25,l=0.05,b=0.0,r=0.05, unit='cm'), 
        legend.spacing.y = unit(0.5, "lines")) 
}
```
Read in the configuration from the jsonl file

```{r include=FALSE}
filename_root="../output/sequence32-2022-05-02-16-13"
jsonl_file <- paste(filename_root, ".jsonl", sep="")
lines <- readLines(jsonl_file)
config <- lapply(lines[1], fromJSON)
config <- lapply(config, unlist)
config <- bind_rows(config)
annotation = str_glue("City size={config$config.city_size} blocks<br>
                      Request rate={config$config.base_demand} per block<br>
                      Trip inhomogeneity={config$config.trip_inhomogeneity}")
```

``` {r echo=FALSE}
sequence <- read_csv(file=str_glue("{filename_root}.csv", sep=""))
sequence$idx <- 1:nrow(sequence)
# convert to a long form
longseq <- melt(sequence, 
                measure.vars = c("vehicle_fraction_idle", 
                                 "vehicle_fraction_picking_up", 
                                 "vehicle_fraction_with_rider", 
                                 "mean_trip_wait_fraction")
                )
```

```{r echo=FALSE}
filename_root="../output/sequence32-2022-05-02-16-18"
sequence_plot(filename_root = filename_root)
```
Create a data frane of P3Max and NMin values

```{r echo=FALSE}
df <- data.frame( city_size=numeric(0), demand=numeric(0), inhomogeneity=character(0), variable=character(0), value=numeric(0))
df <- df %>% add_row(variable="P3_max", city_size=32, demand=1, inhomogeneity="0.0", value=0.54)
df <- df %>% add_row(variable="N_min", city_size=32, demand=1, inhomogeneity="0.0", value=32)
df <- df %>% add_row(variable="P3_max", city_size=32, demand=2, inhomogeneity="0.0", value=0.58)
df <- df %>% add_row(variable="N_min", city_size=32, demand=2, inhomogeneity="0.0", value=70)
df <- df %>% add_row(variable="P3_max", city_size=32, demand=4, inhomogeneity="0.0", value=0.62)
df <- df %>% add_row(variable="N_min", city_size=32, demand=4, inhomogeneity="0.0", value=120)
df <- df %>% add_row(variable="P3_max", city_size=32, demand=8, inhomogeneity="0.0", value=0.64)
df <- df %>% add_row(variable="N_min", city_size=32, demand=8, inhomogeneity="0.0", value=220)
df <- df %>% add_row(variable="P3_max", city_size=32, demand=12, inhomogeneity="0.0", value=0.71)
df <- df %>% add_row(variable="N_min", city_size=32, demand=12, inhomogeneity="0.0", value=300)
df <- df %>% add_row(variable="P3_max", city_size=32, demand=16, inhomogeneity="0.0", value=0.72)
df <- df %>% add_row(variable="N_min", city_size=32, demand=16, inhomogeneity="0.0", value=390)
df <- df %>% add_row(variable="P3_max", city_size=32, demand=20, inhomogeneity="0.0", value=0.73)
df <- df %>% add_row(variable="N_min", city_size=32, demand=20, inhomogeneity="0.0", value=480)
df <- df %>% add_row(variable="P3_max", city_size=32, demand=24, inhomogeneity="0.0", value=0.74)
df <- df %>% add_row(variable="N_min", city_size=32, demand=24, inhomogeneity="0.0", value=560)
df <- df %>% add_row(variable="P3_max", city_size=32, demand=32, inhomogeneity="0.0", value=0.75)
df <- df %>% add_row(variable="N_min", city_size=32, demand=32, inhomogeneity="0.0", value=730)
df <- df %>% add_row(variable="P3_max", city_size=32, demand=40, inhomogeneity="0.0", value=0.76)
df <- df %>% add_row(variable="N_min", city_size=32, demand=40, inhomogeneity="0.0", value=900)
df <- df %>% add_row(variable="P3_max", city_size=32, demand=48, inhomogeneity="0.0", value=0.77)
df <- df %>% add_row(variable="N_min", city_size=32, demand=48, inhomogeneity="0.0", value=1060)
df <- df %>% add_row(variable="P3_max", city_size=32, demand=56, inhomogeneity="0.0", value=0.78)
df <- df %>% add_row(variable="N_min", city_size=32, demand=56, inhomogeneity="0.0", value=1210)
df <- df %>% add_row(variable="P3_max", city_size=32, demand=64, inhomogeneity="0.0", value=0.79)
df <- df %>% add_row(variable="N_min", city_size=32, demand=64, inhomogeneity="0.0", value=1390)
df <- df %>% add_row(variable="P3_max", city_size=32, demand=1, inhomogeneity="0.5", value=0.53)
df <- df %>% add_row(variable="N_min", city_size=32, demand=1, inhomogeneity="0.5", value=34)
df <- df %>% add_row(variable="P3_max", city_size=32, demand=2, inhomogeneity="0.5", value=0.58)
df <- df %>% add_row(variable="N_min", city_size=32, demand=2, inhomogeneity="0.5", value=70)
df <- df %>% add_row(variable="P3_max", city_size=32, demand=8, inhomogeneity="0.5", value=0.62)
df <- df %>% add_row(variable="N_min", city_size=32, demand=8, inhomogeneity="0.5", value=230)
df <- df %>% add_row(variable="P3_max", city_size=32, demand=16, inhomogeneity="0.5", value=0.65)
df <- df %>% add_row(variable="N_min", city_size=32, demand=16, inhomogeneity="0.5", value=430)
df <- df %>% add_row(variable="P3_max", city_size=32, demand=24, inhomogeneity="0.5", value=0.65)
df <- df %>% add_row(variable="N_min", city_size=32, demand=24, inhomogeneity="0.5", value=620)
df <- df %>% add_row(variable="P3_max", city_size=32, demand=32, inhomogeneity="0.5", value=0.68)
df <- df %>% add_row(variable="N_min", city_size=32, demand=32, inhomogeneity="0.5", value=820)
df <- df %>% add_row(variable="P3_max", city_size=32, demand=40, inhomogeneity="0.5", value=0.67)
df <- df %>% add_row(variable="N_min", city_size=32, demand=40, inhomogeneity="0.5", value=1020)
df <- df %>% add_row(variable="P3_max", city_size=32, demand=48, inhomogeneity="0.5", value=0.68)
df <- df %>% add_row(variable="N_min", city_size=32, demand=48, inhomogeneity="0.5", value=1200)
df <- df %>% add_row(variable="P3_max", city_size=32, demand=56, inhomogeneity="0.5", value=0.68)
df <- df %>% add_row(variable="N_min", city_size=32, demand=56, inhomogeneity="0.5", value=1390)
df <- df %>% add_row(variable="P3_max", city_size=32, demand=64, inhomogeneity="0.5", value=0.69)
df <- df %>% add_row(variable="N_min", city_size=32, demand=64, inhomogeneity="0.5", value=1590)
tb <- as_tibble(df)
colours <- c("P3_max" = "royalblue3", "N_min" = "deeppink3")
labels <- c("0.0" = "0.0", "0.5" = "0.5")
p<- ggplot(data=tb, mapping=aes(x=demand, y=value, linetype = inhomogeneity, colour=variable))
p + geom_line(alpha=0.7, size=1) +
  geom_point(alpha=0.7, size=3) +
  scale_colour_manual(values=colours, labels=labels) + 
  # theme(legend.position = "none") +
  facet_wrap(~variable, scales = "free")
```
